# Use DecapBridge PKCE auth (required)
backend:
  name: git-gateway
  repo: pavan-sp/nzaryasamaj
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/420225b5-de4e-42c1-b37f-c4861ff79a39/pkce
  auth_token_endpoint: /sites/420225b5-de4e-42c1-b37f-c4861ff79a39/token
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

site_url: https://nzaryasamaj.netlify.app/preview
display_url: https://www.nzaryasamaj.org/preview

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: content/pages/home.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: About Us
        name: aboutus
        file: content/pages/aboutus.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Contact Us
        name: contactus
        file: content/pages/contactus.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Join Us
        name: joinus
        file: content/pages/joinus.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Executives
        name: executives
        file: content/pages/executives.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Purohits
        name: purohits
        file: content/pages/purohits.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Constitution
        name: constitution
        file: content/pages/constitution.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Gallery
        name: gallery
        file: content/pages/gallery.md
        fields:
          - { label: Body, name: body, widget: markdown }

  - name: events
    label: Events
    files:
      - label: Events List
        name: events_list
        file: /preview/content/events_list.md
        fields:
          - { label: Body, name: body, widget: markdown }

  - name: navigation
    label: Navigation
    files:
      - label: Menu
        name: menu
        file: content/menu.md
        fields:
          - { label: Body, name: body, widget: markdown }
      - label: Sidebar Links
        name: sidebar_links
        file: content/sidebar-links.md
        fields:
          - { label: Body, name: body, widget: markdown }
